server:
  port: 8080

spring:
  application:
    name: trendzy

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017}
      database: trendzy

  datasource:
    url: ${POSTGRES_URL:}
    username: postgres
    password: ${POSTGRES_PASS}

  jpa:
    hibernate:
      ddl-auto: update

  ai:
    openai:
      api-key: ${GROQ_API_KEY:}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
          stream: false

reddit:
  user-agent: "TrendZY/1.0 (by /u/Few_Ganache_1005)"
  subreddits: "IndianFashion,IndianBeautyDeals,streetwear,SkincareAddiction,MakeupAddiction,IndianSkincareRoutine,femalefashionadvice,malefashionadvice,beauty,Hair,fragrance,Sneakers,handbags,IndianFashionAddicts,GenZFashion,Y2Kfashion,cottagecore,IndiaShoppee,frugalmalefashion,30PlusSkinCare"

youtube:
  api-key: ${YOUTUBE_API_KEY:}

jwt:
  secret: ${JWT_SECRET:8y/B?E(G+KbPeShVmYq3t6w9z$C&F)H@McQfTjWnZr4u7x!A%D*G-KaPdSgUkXp2}
  expiration: 604800000

scheduler:
  collection:
    cron: "0 0 2 * * *"
  analysis:
    cron: "0 0 4 * * *"

groq:
  batch-size: 5
  rate-limit-pause-ms: 15000
  daily-token-limit: 95000