/* ═══════════════════════════════════════════════════════════════
   TrendZY — Mock Product Data
   Structure: { id, name, category, score, velocity, tags, image, price, platform, tier, brand? }
   ═══════════════════════════════════════════════════════════════ */

export const MOCK_PRODUCTS = [
  // ── TRENDING (6) ──
  {
    id: 1,
    name: "Adidas Gazelle Bold",
    category: "Sneakers",
    score: 94,
    velocity: "+38%",
    tags: ["#Streetwear", "#GenZ"],
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&h=700&fit=crop",
    price: "₹8,999",
    platform: "Amazon",
    tier: "trending",
    brand: "Adidas",
  },
  {
    id: 2,
    name: "Linen Co-ord Set",
    category: "Co-ords",
    score: 91,
    velocity: "+52%",
    tags: ["#CleanGirl", "#Cottagecore"],
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=700&fit=crop",
    price: "₹2,499",
    platform: "Myntra",
    tier: "trending",
    brand: "H&M",
  },
  {
    id: 3,
    name: "Oversized Mesh Jersey",
    category: "Tops",
    score: 88,
    velocity: "+29%",
    tags: ["#Streetwear", "#Y2K"],
    image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&h=700&fit=crop",
    price: "₹1,799",
    platform: "Amazon",
    tier: "trending",
    brand: "Nike",
  },
  {
    id: 4,
    name: "Ceramic Skin Tint SPF 40",
    category: "Beauty",
    score: 86,
    velocity: "+31%",
    tags: ["#CleanGirl", "#GenZ"],
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&h=700&fit=crop",
    price: "₹1,299",
    platform: "Amazon",
    tier: "trending",
    brand: "Minimalist",
  },
  {
    id: 5,
    name: "Baggy Cargo Pants",
    category: "Pants",
    score: 83,
    velocity: "+24%",
    tags: ["#Gorpcore", "#Streetwear"],
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&h=700&fit=crop",
    price: "₹2,999",
    platform: "Myntra",
    tier: "trending",
    brand: "Uniqlo",
  },
  {
    id: 6,
    name: "Y2K Butterfly Clips Set",
    category: "Accessories",
    score: 78,
    velocity: "+18%",
    tags: ["#Y2K", "#Dopamine"],
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&h=700&fit=crop",
    price: "₹499",
    platform: "Amazon",
    tier: "trending",
    brand: "Zara",
  },

  // ── RISING (5) ──
  {
    id: 7,
    name: "Glass Skin Serum Kit",
    category: "Beauty",
    score: 76,
    velocity: "+67%",
    tags: ["#CleanGirl", "#GenZ"],
    image: "https://images.unsplash.com/photo-1570194065650-d99fb4b38b17?w=600&h=700&fit=crop",
    price: "₹899",
    platform: "Amazon",
    tier: "rising",
    brand: "The Ordinary",
  },
  {
    id: 8,
    name: "Corduroy Shacket",
    category: "Jackets",
    score: 72,
    velocity: "+54%",
    tags: ["#Cottagecore", "#Indie"],
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&h=700&fit=crop",
    price: "₹3,499",
    platform: "Myntra",
    tier: "rising",
    brand: "FabIndia",
  },
  {
    id: 9,
    name: "Chunky Platform Loafers",
    category: "Footwear",
    score: 69,
    velocity: "+47%",
    tags: ["#GenZ", "#Indie"],
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&h=700&fit=crop",
    price: "₹4,999",
    platform: "Amazon",
    tier: "rising",
    brand: "Dr. Martens",
  },
  {
    id: 10,
    name: "Crochet Bucket Hat",
    category: "Accessories",
    score: 65,
    velocity: "+41%",
    tags: ["#Cottagecore", "#Dopamine"],
    image: "https://images.unsplash.com/photo-1521369909029-2afed882baee?w=600&h=700&fit=crop",
    price: "₹699",
    platform: "Amazon",
    tier: "rising",
  },
  {
    id: 11,
    name: "Layered Chain Necklace",
    category: "Jewelry",
    score: 71,
    velocity: "+36%",
    tags: ["#CleanGirl", "#Y2K"],
    image: "https://images.unsplash.com/photo-1599643478518-a920f3ecb379?w=600&h=700&fit=crop",
    price: "₹599",
    platform: "Myntra",
    tier: "rising",
    brand: "Zara",
  },

  // ── CURATED (5) ──
  {
    id: 12,
    name: "Hand-Block Printed Kurta",
    category: "Ethnic",
    score: null,
    velocity: null,
    tags: ["#Indie", "#Cottagecore"],
    image: "https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=600&h=700&fit=crop",
    price: "₹1,899",
    platform: "Brand Site",
    tier: "curated",
    brand: "Okhai",
  },
  {
    id: 13,
    name: "Upcycled Denim Tote",
    category: "Bags",
    score: null,
    velocity: null,
    tags: ["#Indie", "#Gorpcore"],
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&h=700&fit=crop",
    price: "₹1,299",
    platform: "Brand Site",
    tier: "curated",
    brand: "Doodlage",
  },
  {
    id: 14,
    name: "Handwoven Ikat Scarf",
    category: "Accessories",
    score: null,
    velocity: null,
    tags: ["#Indie", "#Cottagecore"],
    image: "https://images.unsplash.com/photo-1601924994987-69e26d50dc64?w=600&h=700&fit=crop",
    price: "₹799",
    platform: "Brand Site",
    tier: "curated",
    brand: "Tjori",
  },
  {
    id: 15,
    name: "Organic Cotton Hoodie",
    category: "Hoodies",
    score: null,
    velocity: null,
    tags: ["#Indie", "#Streetwear"],
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&h=700&fit=crop",
    price: "₹2,199",
    platform: "Brand Site",
    tier: "curated",
    brand: "Nicobar",
  },
  {
    id: 16,
    name: "Artisan Silver Rings Set",
    category: "Jewelry",
    score: null,
    velocity: null,
    tags: ["#Indie", "#CleanGirl"],
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&h=700&fit=crop",
    price: "₹1,499",
    platform: "Brand Site",
    tier: "curated",
    brand: "Tribe Amrapali",
  },
];

/* ── Selectors ── */
export const getTrending = () => MOCK_PRODUCTS.filter(p => p.tier === "trending");
export const getRising   = () => MOCK_PRODUCTS.filter(p => p.tier === "rising");
export const getCurated  = () => MOCK_PRODUCTS.filter(p => p.tier === "curated");

/* Ticker data — name + velocity */
export const getTickerItems = () =>
  MOCK_PRODUCTS
    .filter(p => p.velocity)
    .map(p => ({ name: p.name, velocity: p.velocity }));

/* Legacy exports for backward compatibility with existing API client */
export const mockTrends = MOCK_PRODUCTS.filter(p => p.tier !== "curated").map(p => ({
  id: p.id,
  productName: p.name,
  category: p.category.toLowerCase(),
  trendScore: p.score ? p.score / 10 : 5,
  velocity: p.velocity ? parseFloat(p.velocity) / 10 : 0.5,
  velocityLabel: p.tier === "rising" ? "Rising Fast" : "Trending Now",
  confidence: p.score ? p.score / 100 : 0.7,
  aiExplanation: `Trending product detected across multiple signals.`,
  mentionCountThisWeek: Math.floor(Math.random() * 3000) + 500,
  mentionCountLastWeek: Math.floor(Math.random() * 800) + 200,
  audienceTag: "genz",
  brandMention: p.brand || null,
  pricePoint: "mid-range",
  gender: "unisex",
  indiaRelevant: true,
  imageUrl: p.image,
  vibeTags: p.tags.map(t => t.replace('#', '')),
  productLinks: [
    { id: p.id * 10, platform: "Amazon", affiliateUrl: "https://amazon.in", priceRange: p.price },
    { id: p.id * 10 + 1, platform: "Myntra", affiliateUrl: "https://myntra.com", priceRange: p.price },
  ],
}));

export const mockCategories = ["fashion", "beauty", "tech", "lifestyle"];
