package com.trendzy.ingestion.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "token_usage")
public class TokenUsage {
    @Id
    private String id;

    private String signalId; // The raw signal that triggered this LLM call
    private String aiModel;  // e.g., "llama3-8b-8192"

    private int promptTokens; // Tokens sent to LLM
    private int completionTokens; // Tokens generated by LLM
    private int totalTokens;

    private String operationType; // e.g., "TREND_EXTRACTION", "AESTHETIC_MAPPING"
    private Instant timestamp;
}