package com.trendzy.scraper.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Final product DTO returned by the scraping pipeline.
 *
 * <p>Field names and types exactly match the required JSON schema:
 * <pre>
 * {
 *   "category":    "",
 *   "productType": "",
 *   "brandName":   "",
 *   "productName": "",
 *   "imageUrl":    "",
 *   "websiteLink": "",
 *   "priceInr":    0,
 *   "priceRange":  "",
 *   "description": "",
 *   "featured":    false,
 *   "vibeTags":    []
 * }
 * </pre>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ProductDto {

    /** High-level style category: Streetwear, Y2K, Sustainable, etc. */
    private String category;

    /** Specific item type: T-Shirt, Hoodie, Cargo Pants, Sneaker, etc. */
    private String productType;

    /** Brand / shop name. */
    private String brandName;

    /** Individual product name. */
    private String productName;

    /** Full CDN URL to a product image. */
    private String imageUrl;

    /** Direct product page URL (no affiliate tags). */
    private String websiteLink;

    /** Price in Indian Rupees. */
    private int priceInr;

    /**
     * Human-readable price band, e.g. {@code "800-1200"}.
     * Auto-generated by the pipeline — not scraped directly.
     */
    private String priceRange;

    /** 8–15 word product description. */
    private String description;

    /** Whether this should be surfaced as a featured/hero product. */
    @Builder.Default
    private boolean featured = false;

    /** Exactly 3 vibe hashtag strings, e.g. {@code ["Streetwear", "GenZ", "Oversized"]}. */
    @Builder.Default
    private List<String> vibeTags = List.of();
}